# Generated by Django 5.2.11 on 2026-02-12 19:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('requereix_refrigeracio', models.BooleanField(default=False)),
                ('temperatura_maxima', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura màxima permesa (null si no requereix)', max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_client', models.CharField(help_text='Codi del client', max_length=20, unique=True)),
                ('nom_comercial', models.CharField(max_length=255)),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('persona_contacte', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adreca_entrega', models.CharField(max_length=255)),
                ('poblacio', models.CharField(max_length=100)),
                ('codi_postal', models.CharField(max_length=10)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Magatzem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('adreca', models.CharField(max_length=255)),
                ('capacitat_maxima', models.DecimalField(decimal_places=2, help_text='Capacitat en m³', max_digits=10)),
                ('te_cambra_frio', models.BooleanField(default=False)),
                ('responsable', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Magatzems',
            },
        ),
        migrations.CreateModel(
            name='Empleat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_empleat', models.CharField(help_text='Codi únic (ex: EMP001)', max_length=20, unique=True)),
                ('telefon', models.CharField(max_length=20)),
                ('data_alta', models.DateField(auto_now_add=True)),
                ('carrec', models.CharField(help_text='Ex: Preparador, Repartidor, Administrador', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleat', to=settings.AUTH_USER_MODEL)),
                ('magatzem_assignat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleats', to='albaranes.magatzem')),
            ],
            options={
                'verbose_name_plural': 'Empleats',
            },
        ),
        migrations.CreateModel(
            name='Albara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_albara', models.CharField(help_text="Número únic d'albarà (ex: ALB-2024-001)", max_length=30, unique=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateField()),
                ('estat', models.CharField(choices=[('PENDENT', 'Pendent'), ('EN_PREPARACIO', 'En preparació'), ('PREPARAT', 'Preparat'), ('ENVIAT', 'Enviat'), ('ENTREGAT', 'Entregat'), ('CANCELAT', 'Cancel·lat')], default='PENDENT', max_length=20)),
                ('base_imposable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('signatura_client', models.CharField(blank=True, help_text='Nom de qui signa (null si no està entregat)', max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albarans', to='albaranes.client')),
                ('empleat', models.ForeignKey(help_text="Qui prepara l'albarà", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albarans', to='albaranes.empleat')),
                ('magatzem', models.ForeignKey(blank=True, help_text="D'on surt la mercaderia", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albarans', to='albaranes.magatzem')),
            ],
            options={
                'verbose_name': 'Albarà',
                'verbose_name_plural': 'Albarans',
                'ordering': ['-data_creacio'],
            },
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(help_text='Codi únic del producte (ex: BEB001)', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unitat_mesura', models.CharField(choices=[('UNITAT', 'Unitat'), ('CAIXA', 'Caixa'), ('PALET', 'Palet'), ('KG', 'Kg'), ('LITRE', 'Litre')], default='UNITAT', max_length=10)),
                ('iva', models.DecimalField(choices=[(Decimal('0.04'), '4%'), (Decimal('0.10'), '10%'), (Decimal('0.21'), '21%')], decimal_places=2, default=Decimal('0.21'), max_digits=4)),
                ('es_perible', models.BooleanField(default=False, help_text='Indica si caduca aviat')),
                ('imatge_url', models.URLField(blank=True, null=True)),
                ('actiu', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productes', to='albaranes.categoria')),
            ],
            options={
                'verbose_name_plural': 'Productes',
            },
        ),
        migrations.CreateModel(
            name='MovimentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SORTIDA', 'Sortida'), ('AJUST', 'Ajust')], max_length=10)),
                ('quantitat', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('albara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviments_stock', to='albaranes.albara')),
                ('magatzem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviments', to='albaranes.magatzem')),
                ('usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviments', to='albaranes.producte')),
            ],
            options={
                'verbose_name': "Moviment d'Stock",
                'verbose_name_plural': "Moviments d'Stock",
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='LiniaAlbara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producte', models.CharField(max_length=255)),
                ('quantitat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.21'), max_digits=4)),
                ('descompte_percentatge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descompte aplicat (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('observacions', models.CharField(blank=True, help_text='Notes especials (ex: substituir si no hi ha stock)', max_length=255, null=True)),
                ('albara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='albaranes.albara')),
                ('producte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linies_albara', to='albaranes.producte')),
            ],
            options={
                'verbose_name': "Línia d'Albarà",
                'verbose_name_plural': "Línies d'Albarà",
            },
        ),
        migrations.CreateModel(
            name='StockMagatzem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_ultima_entrada', models.DateField(auto_now=True)),
                ('ubicacio', models.CharField(help_text='Passadís/estanteria (ex: A-12)', max_length=20)),
                ('magatzem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='albaranes.magatzem')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='albaranes.producte')),
            ],
            options={
                'verbose_name': 'Stock de Magatzem',
                'verbose_name_plural': 'Stocks de Magatzems',
                'unique_together': {('producte', 'magatzem')},
            },
        ),
        migrations.AddField(
            model_name='producte',
            name='magatzems',
            field=models.ManyToManyField(related_name='productes', through='albaranes.StockMagatzem', to='albaranes.magatzem'),
        ),
    ]
